#!/bin/bash

## Description: Initialization for extensions and site config
## Usage: initialization
## Example: "ddev initialization"
YELLOW="\033[1;33m"
NONE="\033[0m"
GREEN="\033[1;32m"

ddev describe
echo -e "${YELLOW}DDEV Initialization is done, your next environment can now be started with: ${GREEN}ddev exec pnpm dev${NONE}"

exit 0
